# Updated as of Aug 16, 2017
FROM tomcat:8.5

#Author of the Docker File
LABEL "Maintainer"="f-sanges"

# Copy the following directory
COPY docker-spring-mvc.war /usr/local/tomcat/webapps/docker-spring-mvc.war